on:
  pull_request:
    types: [ready_for_review]
jobs:
  notify:
    runs-on: ubuntu-latest
    name: notify chat
    steps:
    - name: Google Chat Notification
      uses: Co-qn/google-chat-notification@releases/v1
      with:
        name: Pull request review
        url: https://chat.googleapis.com/v1/spaces/AAAA_iUfT18/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=Qnrj63BATEim_jN7dwfOIg_dS8AB78TgZQTsRBDIJ5g%3D
        status: opened
      if: always()
     